### ISSUE TITLE
Failed to connect error with Kahoot-Profane.

### ISSUE THREAD

**Issue by ElliotGluck** [unixpickle/kahoot-hack#96] opened 2017-05-07 23:18 UTC
I was testing Kahoot-profane last night and it worked flawlessly. When I tried to use it today, I got the following error:
`failed to connect: failed to create session: parse session challenge: invalid character '<' looking for beginning of value`
I tried pinging kahoot.it and my IP doesn't seem to be blocked. Was kahoot-profane patched or is there something wrong with my setup?

**Comment by jonasvanderschaaf** [comment] 2017-05-11 20:01
Does it give the line number where error occurred?

**Comment by unixpickle** [comment] 2017-05-12 01:44
@jonasvanderschaaf I doubt it, but it's pretty clear where the error came from judging by the message. That error happens when the server sends back an HTML page and we try to parse it as JSON. Why the server is doing that is a different story.

**Comment by unixpickle** [comment] 2017-08-13 01:43
I'm going to close this since nobody has reproduced it and there's tons of other issues where people are having trouble. If you post more info, perhaps I will re-open this:

 * Does this happen for the other tools?
 * Are you running this on a school's network (behind a firewall)?

**Closed by unixpickle** 2017-08-13 01:43 UTC
