### ISSUE TITLE
Any way to make the bot appear as have answered the question during the countdown?

### ISSUE THREAD

**Issue by ghost** [unixpickle/kahoot-hack#129] opened 2017-10-30 17:50 UTC
![0-1](https://user-images.githubusercontent.com/33165493/32186637-f98a5b92-bd78-11e7-8740-eff574aa5bc0.PNG)

During the countdown, it does not show that the bot has answered.

![1](https://user-images.githubusercontent.com/33165493/32186639-fdc96018-bd78-11e7-960b-428aa0539e87.PNG)

Only afterwards in the scoreboard screen does it show the bot. Is there any way to change this?

**Comment by SenorWhale** [comment] 2018-01-10 00:34
If there is a way to do this I'd really like to know, it's kind of annoying with the answers not showing up. Unless there's some important reason they don't show up, then whatever.

**Comment by unixpickle** [comment] 2018-01-11 01:23
It used to work fine. My guess is that Kahoot intentionally detects bots and doesn't show them.

**Comment by unixpickle** [comment] 2018-05-14 01:46
This should be fixed by #140 (duplicate of #141 and #137)

**Closed by unixpickle** 2018-05-14 01:46 UTC
